
   ALTER TABLE usuario_perfil ADD  FOREIGN KEY (usuarioID) REFERENCES usuario (id) ON UPDATE CASCADE ON DELETE RESTRICT;
   ALTER TABLE usuario_perfil ADD  FOREIGN KEY (perfilID) REFERENCES perfil (id) ON UPDATE CASCADE ON DELETE RESTRICT;   